jwt:
  secret-key: MY_SECRET_KEY
server:
  port: 8081
  servlet:
    context-path:
      /chat

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: izobretatel7777@gmail.com
    password: ${SPRING_MAIL_PASSWROD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
current:
  url: ${CURRENT_URL:http://localhost}:${server.port}${server.servlet.context-path}