jwt:
  secret-key: MY_SECRET_KEY
server:
  port: 8081
  servlet:
    context-path:
      /chat

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/chat-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
    hibernate:
      ddl-auto: update

    liquibase:
      enabled: true
      drop-first: FALSE
      database-change-log-table: DATABASECHANGELOG
      database-change-log-lock-table: DATABASECHANGELOGLOCK
